name: "Build Blocksumo (native)"

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'messaging/**'
      - 'core/**'
      - '.github/workflows/build-blocksumo-native.yaml'
      - 'blocksumo/**'
      - 'build.gradle.kts'

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - uses: "graalvm/setup-graalvm@v1"
        with:
          java-version: "25"
          distribution: "graalvm-community"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          cache: "gradle"
          native-image-job-reports: "true"

      - uses: "emortalmc/actions/java/build@main"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          project: "blocksumo-native"
          gradle-command: "./gradlew blocksumo:nativeCompile --no-daemon"
          dockerfile-path: './blocksumo/Dockerfile.native'
          dockerfile-context: './blocksumo/'
